//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsuarioMVC.ServicioUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/ServicioUsuario.Modelos")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                if ((object.ReferenceEquals(this.sexoField, value) != true)) {
                    this.sexoField = value;
                    this.RaisePropertyChanged("sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioUsuario.IUsuarioService")]
    public interface IUsuarioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Actualizar", ReplyAction="http://tempuri.org/IUsuarioService/ActualizarResponse")]
        bool Actualizar(string Nombre, string FechaNacimiento, string Sexo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Actualizar", ReplyAction="http://tempuri.org/IUsuarioService/ActualizarResponse")]
        System.Threading.Tasks.Task<bool> ActualizarAsync(string Nombre, string FechaNacimiento, string Sexo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Agregar", ReplyAction="http://tempuri.org/IUsuarioService/AgregarResponse")]
        bool Agregar(string Nombre, string FechaNacimiento, string Sexo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Agregar", ReplyAction="http://tempuri.org/IUsuarioService/AgregarResponse")]
        System.Threading.Tasks.Task<bool> AgregarAsync(string Nombre, string FechaNacimiento, string Sexo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Buscar", ReplyAction="http://tempuri.org/IUsuarioService/BuscarResponse")]
        UsuarioMVC.ServicioUsuario.Usuario Buscar(string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Buscar", ReplyAction="http://tempuri.org/IUsuarioService/BuscarResponse")]
        System.Threading.Tasks.Task<UsuarioMVC.ServicioUsuario.Usuario> BuscarAsync(string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Consultar", ReplyAction="http://tempuri.org/IUsuarioService/ConsultarResponse")]
        UsuarioMVC.ServicioUsuario.Usuario[] Consultar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Consultar", ReplyAction="http://tempuri.org/IUsuarioService/ConsultarResponse")]
        System.Threading.Tasks.Task<UsuarioMVC.ServicioUsuario.Usuario[]> ConsultarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Eliminar", ReplyAction="http://tempuri.org/IUsuarioService/EliminarResponse")]
        bool Eliminar(string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Eliminar", ReplyAction="http://tempuri.org/IUsuarioService/EliminarResponse")]
        System.Threading.Tasks.Task<bool> EliminarAsync(string Nombre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioServiceChannel : UsuarioMVC.ServicioUsuario.IUsuarioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioServiceClient : System.ServiceModel.ClientBase<UsuarioMVC.ServicioUsuario.IUsuarioService>, UsuarioMVC.ServicioUsuario.IUsuarioService {
        
        public UsuarioServiceClient() {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Actualizar(string Nombre, string FechaNacimiento, string Sexo) {
            return base.Channel.Actualizar(Nombre, FechaNacimiento, Sexo);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarAsync(string Nombre, string FechaNacimiento, string Sexo) {
            return base.Channel.ActualizarAsync(Nombre, FechaNacimiento, Sexo);
        }
        
        public bool Agregar(string Nombre, string FechaNacimiento, string Sexo) {
            return base.Channel.Agregar(Nombre, FechaNacimiento, Sexo);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarAsync(string Nombre, string FechaNacimiento, string Sexo) {
            return base.Channel.AgregarAsync(Nombre, FechaNacimiento, Sexo);
        }
        
        public UsuarioMVC.ServicioUsuario.Usuario Buscar(string Nombre) {
            return base.Channel.Buscar(Nombre);
        }
        
        public System.Threading.Tasks.Task<UsuarioMVC.ServicioUsuario.Usuario> BuscarAsync(string Nombre) {
            return base.Channel.BuscarAsync(Nombre);
        }
        
        public UsuarioMVC.ServicioUsuario.Usuario[] Consultar() {
            return base.Channel.Consultar();
        }
        
        public System.Threading.Tasks.Task<UsuarioMVC.ServicioUsuario.Usuario[]> ConsultarAsync() {
            return base.Channel.ConsultarAsync();
        }
        
        public bool Eliminar(string Nombre) {
            return base.Channel.Eliminar(Nombre);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarAsync(string Nombre) {
            return base.Channel.EliminarAsync(Nombre);
        }
    }
}
